export type TrainClass = {
  code: string;
  fare: number;
  available: number;
  probability: number;
};

export type Train = {
  id: string;
  name: string;
  number: string;
  from: string;
  fromCode: string;
  to: string;
  toCode: string;
  depart: string;
  arrive: string;
  duration: string;
  classes: TrainClass[];
  type: "Rajdhani" | "Shatabdi" | "Superfast" | "Express" | "Vande Bharat";
  tags?: string[];
};

export const trains: Train[] = [
  {
    id: "t1",
    name: "Vande Bharat Express",
    number: "22439",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Jaipur Junction",
    toCode: "JP",
    depart: "06:10",
    arrive: "10:35",
    duration: "4h 25m",
    type: "Vande Bharat",
    tags: ["Fastest", "Onboard catering"],
    classes: [
      { code: "CC", fare: 1245, available: 42, probability: 98 },
      { code: "EC", fare: 2340, available: 12, probability: 96 },
    ],
  },
  {
    id: "t2",
    name: "Ajmer Shatabdi",
    number: "12015",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Jaipur Junction",
    toCode: "JP",
    depart: "06:05",
    arrive: "10:40",
    duration: "4h 35m",
    type: "Shatabdi",
    tags: ["AC", "Breakfast included"],
    classes: [
      { code: "CC", fare: 970, available: 118, probability: 99 },
      { code: "EC", fare: 1815, available: 24, probability: 97 },
    ],
  },
  {
    id: "t3",
    name: "Jaipur Double Decker",
    number: "12985",
    from: "Delhi Sarai Rohilla",
    fromCode: "DEE",
    to: "Jaipur Junction",
    toCode: "JP",
    depart: "05:40",
    arrive: "10:20",
    duration: "4h 40m",
    type: "Superfast",
    tags: ["AC Chair Car"],
    classes: [
      { code: "CC", fare: 720, available: 6, probability: 62 },
    ],
  },
  {
    id: "t4",
    name: "Ashram Express",
    number: "12916",
    from: "Old Delhi",
    fromCode: "DLI",
    to: "Jaipur Junction",
    toCode: "JP",
    depart: "15:20",
    arrive: "20:55",
    duration: "5h 35m",
    type: "Superfast",
    tags: ["Sleeper"],
    classes: [
      { code: "SL", fare: 285, available: 0, probability: 34 },
      { code: "3A", fare: 755, available: 3, probability: 48 },
      { code: "2A", fare: 1080, available: 0, probability: 22 },
    ],
  },
  {
    id: "t5",
    name: "Mumbai Rajdhani",
    number: "12952",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Mumbai Central",
    toCode: "MMCT",
    depart: "16:55",
    arrive: "08:35",
    duration: "15h 40m",
    type: "Rajdhani",
    tags: ["Meals included"],
    classes: [
      { code: "1A", fare: 4200, available: 8, probability: 94 },
      { code: "2A", fare: 2500, available: 31, probability: 91 },
      { code: "3A", fare: 1780, available: 67, probability: 95 },
    ],
  },
  {
    id: "t6",
    name: "Pune Duronto",
    number: "12220",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Pune Junction",
    toCode: "PUNE",
    depart: "22:10",
    arrive: "14:25",
    duration: "16h 15m",
    type: "Superfast",
    classes: [
      { code: "2A", fare: 2350, available: 18, probability: 88 },
      { code: "3A", fare: 1650, available: 42, probability: 92 },
    ],
  },
  {
    id: "t7",
    name: "Karnataka Express",
    number: "12628",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "KSR Bengaluru",
    toCode: "SBC",
    depart: "21:15",
    arrive: "06:40",
    duration: "33h 25m",
    type: "Express",
    classes: [
      { code: "SL", fare: 850, available: 94, probability: 76 },
      { code: "3A", fare: 2050, available: 31, probability: 88 },
      { code: "2A", fare: 2950, available: 12, probability: 91 },
    ],
  },
  {
    id: "t8",
    name: "Chennai Rajdhani",
    number: "12434",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Chennai Central",
    toCode: "MAS",
    depart: "15:55",
    arrive: "09:30",
    duration: "17h 35m",
    type: "Rajdhani",
    classes: [
      { code: "1A", fare: 4350, available: 5, probability: 94 },
      { code: "2A", fare: 2600, available: 22, probability: 92 },
      { code: "3A", fare: 1850, available: 49, probability: 95 },
    ],
  },
  {
    id: "t9",
    name: "Howrah Rajdhani",
    number: "12302",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Howrah Junction",
    toCode: "HWH",
    depart: "17:00",
    arrive: "10:00",
    duration: "17h",
    type: "Rajdhani",
    classes: [
      { code: "1A", fare: 4100, available: 7, probability: 95 },
      { code: "2A", fare: 2450, available: 27, probability: 93 },
      { code: "3A", fare: 1720, available: 61, probability: 96 },
    ],
  },
  {
    id: "t10",
    name: "Bhopal Shatabdi",
    number: "12002",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Bhopal Junction",
    toCode: "BPL",
    depart: "06:00",
    arrive: "14:00",
    duration: "8h",
    type: "Shatabdi",
    classes: [
      { code: "CC", fare: 1250, available: 84, probability: 97 },
      { code: "EC", fare: 2450, available: 16, probability: 94 },
    ],
  },
  {
    id: "t11",
    name: "Lucknow Shatabdi",
    number: "12004",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Lucknow",
    toCode: "LKO",
    depart: "06:10",
    arrive: "12:45",
    duration: "6h 35m",
    type: "Shatabdi",
    classes: [
      { code: "CC", fare: 1050, available: 76, probability: 98 },
      { code: "EC", fare: 1990, available: 14, probability: 96 },
    ],
  },
  {
    id: "t12",
    name: "Amritsar Shatabdi",
    number: "12029",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Amritsar Junction",
    toCode: "ASR",
    depart: "07:20",
    arrive: "13:45",
    duration: "6h 25m",
    type: "Shatabdi",
    classes: [
      { code: "CC", fare: 980, available: 64, probability: 97 },
      { code: "EC", fare: 1850, available: 11, probability: 95 },
    ],
  },
  {
    id: "t13",
    name: "Gujarat Mail",
    number: "12902",
    from: "Ahmedabad Junction",
    fromCode: "ADI",
    to: "Mumbai Central",
    toCode: "MMCT",
    depart: "22:00",
    arrive: "06:30",
    duration: "8h 30m",
    type: "Express",
    classes: [
      { code: "SL", fare: 430, available: 132, probability: 89 },
      { code: "3A", fare: 1120, available: 43, probability: 94 },
      { code: "2A", fare: 1580, available: 18, probability: 91 },
    ],
  },
  {
    id: "t14",
    name: "Deccan Queen",
    number: "12124",
    from: "Mumbai Central",
    fromCode: "MMCT",
    to: "Pune Junction",
    toCode: "PUNE",
    depart: "07:10",
    arrive: "10:25",
    duration: "3h 15m",
    type: "Express",
    classes: [
      { code: "CC", fare: 560, available: 72, probability: 97 },
      { code: "EC", fare: 980, available: 12, probability: 93 },
    ],
  },
  {
    id: "t15",
    name: "Hyderabad Express",
    number: "12702",
    from: "Mumbai Central",
    fromCode: "MMCT",
    to: "Hyderabad",
    toCode: "HYB",
    depart: "18:45",
    arrive: "10:20",
    duration: "15h 35m",
    type: "Superfast",
    classes: [
      { code: "SL", fare: 620, available: 98, probability: 84 },
      { code: "3A", fare: 1450, available: 38, probability: 91 },
      { code: "2A", fare: 2080, available: 14, probability: 88 },
    ],
  },
  {
    id: "t16",
    name: "Mysuru Express",
    number: "12614",
    from: "Chennai Central",
    fromCode: "MAS",
    to: "Mysuru Junction",
    toCode: "MYS",
    depart: "21:15",
    arrive: "06:45",
    duration: "9h 30m",
    type: "Express",
    classes: [
      { code: "SL", fare: 420, available: 88, probability: 91 },
      { code: "3A", fare: 980, available: 29, probability: 94 },
    ],
  },
  {
    id: "t17",
    name: "Coromandel Express",
    number: "12842",
    from: "Chennai Central",
    fromCode: "MAS",
    to: "Howrah Junction",
    toCode: "HWH",
    depart: "07:00",
    arrive: "14:20",
    duration: "27h 20m",
    type: "Superfast",
    classes: [
      { code: "SL", fare: 720, available: 110, probability: 87 },
      { code: "3A", fare: 1680, available: 45, probability: 93 },
      { code: "2A", fare: 2380, available: 19, probability: 91 },
    ],
  },
  {
    id: "t18",
    name: "Patna Rajdhani",
    number: "12310",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Patna Junction",
    toCode: "PNBE",
    depart: "17:15",
    arrive: "07:40",
    duration: "14h 25m",
    type: "Rajdhani",
    classes: [
      { code: "1A", fare: 3650, available: 6, probability: 94 },
      { code: "2A", fare: 2200, available: 25, probability: 92 },
      { code: "3A", fare: 1550, available: 54, probability: 95 },
    ],
  },
  {
    id: "t19",
    name: "Gorakhpur Express",
    number: "12556",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Gorakhpur",
    toCode: "GKP",
    depart: "20:00",
    arrive: "08:30",
    duration: "12h 30m",
    type: "Express",
    classes: [
      { code: "SL", fare: 490, available: 124, probability: 82 },
      { code: "3A", fare: 1180, available: 41, probability: 90 },
      { code: "2A", fare: 1690, available: 15, probability: 87 },
    ],
  },
  {
    id: "t20",
    name: "Udaipur City Express",
    number: "12964",
    from: "Delhi Sarai Rohilla",
    fromCode: "DEE",
    to: "Udaipur City",
    toCode: "UDZ",
    depart: "19:30",
    arrive: "07:15",
    duration: "11h 45m",
    type: "Superfast",
    classes: [
      { code: "SL", fare: 460, available: 75, probability: 88 },
      { code: "3A", fare: 1120, available: 32, probability: 93 },
      { code: "2A", fare: 1590, available: 10, probability: 89 },
    ],
  },
  {
    id: "t21",
    name: "Ranchi Express",
    number: "12826",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Ranchi",
    toCode: "RNC",
    depart: "16:30",
    arrive: "09:20",
    duration: "16h 50m",
    type: "Express",
    classes: [
      { code: "SL", fare: 590, available: 101, probability: 85 },
      { code: "3A", fare: 1420, available: 37, probability: 91 },
    ],
  },
  {
    id: "t22",
    name: "Guwahati Rajdhani",
    number: "12424",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Guwahati",
    toCode: "GHY",
    depart: "16:55",
    arrive: "07:30",
    duration: "38h 35m",
    type: "Rajdhani",
    classes: [
      { code: "1A", fare: 4700, available: 5, probability: 92 },
      { code: "2A", fare: 2850, available: 19, probability: 90 },
      { code: "3A", fare: 1980, available: 42, probability: 94 },
    ],
  },
  {
    id: "t23",
    name: "Goa Express",
    number: "12780",
    from: "Hazrat Nizamuddin",
    fromCode: "NZM",
    to: "Madgaon",
    toCode: "MAO",
    depart: "15:10",
    arrive: "09:00",
    duration: "41h 50m",
    type: "Superfast",
    classes: [
      { code: "SL", fare: 920, available: 83, probability: 79 },
      { code: "3A", fare: 2050, available: 27, probability: 88 },
      { code: "2A", fare: 2980, available: 9, probability: 85 },
    ],
  },
  {
    id: "t24",
    name: "Kerala Express",
    number: "12626",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Thiruvananthapuram Central",
    toCode: "TVC",
    depart: "11:25",
    arrive: "13:10",
    duration: "49h 45m",
    type: "Superfast",
    classes: [
      { code: "SL", fare: 1050, available: 117, probability: 81 },
      { code: "3A", fare: 2380, available: 36, probability: 90 },
      { code: "2A", fare: 3450, available: 13, probability: 87 },
    ],
  },
  {
    id: "t25",
    name: "Golden Temple Mail",
    number: "12904",
    from: "Mumbai Central",
    fromCode: "MMCT",
    to: "New Delhi",
    toCode: "NDLS",
    depart: "18:45",
    arrive: "11:20",
    duration: "16h 35m",
    type: "Superfast",
    classes: [
      { code: "SL", fare: 610, available: 91, probability: 89 },
      { code: "3A", fare: 1480, available: 35, probability: 94 },
      { code: "2A", fare: 2140, available: 16, probability: 91 },
    ],
  },
  {
    id: "t26",
    name: "Ahmedabad Vande Bharat",
    number: "20902",
    from: "Mumbai Central",
    fromCode: "MMCT",
    to: "Ahmedabad Junction",
    toCode: "ADI",
    depart: "06:00",
    arrive: "11:25",
    duration: "5h 25m",
    type: "Vande Bharat",
    classes: [
      { code: "CC", fare: 1280, available: 54, probability: 98 },
      { code: "EC", fare: 2380, available: 15, probability: 96 },
    ],
  },
  {
    id: "t27",
    name: "Varanasi Vande Bharat",
    number: "22416",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Varanasi Junction",
    toCode: "BSB",
    depart: "06:00",
    arrive: "14:00",
    duration: "8h",
    type: "Vande Bharat",
    classes: [
      { code: "CC", fare: 1800, available: 48, probability: 97 },
      { code: "EC", fare: 3350, available: 11, probability: 95 },
    ],
  },
  {
    id: "t28",
    name: "Nagpur Duronto",
    number: "12290",
    from: "Mumbai Central",
    fromCode: "MMCT",
    to: "Nagpur Junction",
    toCode: "NGP",
    depart: "20:00",
    arrive: "07:40",
    duration: "11h 40m",
    type: "Superfast",
    classes: [
      { code: "2A", fare: 2150, available: 22, probability: 91 },
      { code: "3A", fare: 1510, available: 46, probability: 94 },
    ],
  },
  {
    id: "t29",
    name: "Indore Intercity",
    number: "19302",
    from: "Bhopal Junction",
    fromCode: "BPL",
    to: "Indore Junction",
    toCode: "INDB",
    depart: "06:30",
    arrive: "11:00",
    duration: "4h 30m",
    type: "Express",
    classes: [
      { code: "CC", fare: 620, available: 87, probability: 96 },
      { code: "SL", fare: 250, available: 121, probability: 98 },
    ],
  },
  {
    id: "t30",
    name: "Jammu Rajdhani",
    number: "12426",
    from: "New Delhi",
    fromCode: "NDLS",
    to: "Jammu Tawi",
    toCode: "JAT",
    depart: "20:10",
    arrive: "05:00",
    duration: "8h 50m",
    type: "Rajdhani",
    classes: [
      { code: "1A", fare: 3100, available: 6, probability: 94 },
      { code: "2A", fare: 1850, available: 24, probability: 92 },
      { code: "3A", fare: 1320, available: 58, probability: 95 },
    ],
  },
];

// ============================================================
// BUS ROUTES
// ============================================================

export type BusRoute = {
  id: string;
  operator: string;
  busNumber: string;
  from: string;
  fromCode: string;
  to: string;
  toCode: string;
  depart: string;
  arrive: string;
  duration: string;
  busType: "AC Sleeper" | "AC Seater" | "Volvo AC" | "Non-AC Seater";
  fare: number;
  seatsAvailable: number;
  amenities: string[];
};

export const busRoutes: BusRoute[] = [
  {
    id: "b1",
    operator: "RSRTC",
    busNumber: "RJ14-001",
    from: "Delhi ISBT",
    fromCode: "ISBT",
    to: "Jaipur",
    toCode: "JAI",
    depart: "22:00",
    arrive: "06:30",
    duration: "8h 30m",
    busType: "Volvo AC",
    fare: 899,
    seatsAvailable: 14,
    amenities: ["Wi-Fi", "Charging", "Water"],
  },
  {
    id: "b2",
    operator: "UPSRTC",
    busNumber: "UP32-102",
    from: "Delhi ISBT",
    fromCode: "ISBT",
    to: "Lucknow",
    toCode: "LKO",
    depart: "20:30",
    arrive: "07:00",
    duration: "10h 30m",
    busType: "AC Sleeper",
    fare: 1299,
    seatsAvailable: 18,
    amenities: ["Charging", "Blanket"],
  },
  {
    id: "b3",
    operator: "HRTC",
    busNumber: "HP01-301",
    from: "Delhi",
    fromCode: "DEL",
    to: "Chandigarh",
    toCode: "CDG",
    depart: "07:30",
    arrive: "12:00",
    duration: "4h 30m",
    busType: "Volvo AC",
    fare: 699,
    seatsAvailable: 22,
    amenities: ["Wi-Fi", "Charging"],
  },
  {
    id: "b4",
    operator: "RSRTC",
    busNumber: "RJ14-204",
    from: "Delhi",
    fromCode: "DEL",
    to: "Udaipur",
    toCode: "UDR",
    depart: "19:30",
    arrive: "07:30",
    duration: "12h",
    busType: "AC Sleeper",
    fare: 1399,
    seatsAvailable: 12,
    amenities: ["Blanket", "Charging"],
  },
  {
    id: "b5",
    operator: "MSRTC",
    busNumber: "MH12-505",
    from: "Mumbai",
    fromCode: "BOM",
    to: "Pune",
    toCode: "PUN",
    depart: "08:00",
    arrive: "11:30",
    duration: "3h 30m",
    busType: "Volvo AC",
    fare: 549,
    seatsAvailable: 31,
    amenities: ["Charging", "Water"],
  },
  {
    id: "b6",
    operator: "MSRTC",
    busNumber: "MH14-601",
    from: "Mumbai",
    fromCode: "BOM",
    to: "Nashik",
    toCode: "ISK",
    depart: "09:30",
    arrive: "14:30",
    duration: "5h",
    busType: "AC Seater",
    fare: 499,
    seatsAvailable: 28,
    amenities: ["Charging"],
  },
  {
    id: "b7",
    operator: "VRL Travels",
    busNumber: "KA01-701",
    from: "Bengaluru",
    fromCode: "BLR",
    to: "Chennai",
    toCode: "MAA",
    depart: "22:30",
    arrive: "05:30",
    duration: "7h",
    busType: "AC Sleeper",
    fare: 1099,
    seatsAvailable: 17,
    amenities: ["Wi-Fi", "Blanket", "Charging"],
  },
  {
    id: "b8",
    operator: "KSRTC",
    busNumber: "KA09-801",
    from: "Bengaluru",
    fromCode: "BLR",
    to: "Mysuru",
    toCode: "MYS",
    depart: "07:00",
    arrive: "10:00",
    duration: "3h",
    busType: "Volvo AC",
    fare: 449,
    seatsAvailable: 35,
    amenities: ["Charging", "Water"],
  },
  {
    id: "b9",
    operator: "TSRTC",
    busNumber: "TS10-901",
    from: "Hyderabad",
    fromCode: "HYD",
    to: "Vijayawada",
    toCode: "BZA",
    depart: "21:00",
    arrive: "05:00",
    duration: "8h",
    busType: "AC Sleeper",
    fare: 999,
    seatsAvailable: 16,
    amenities: ["Blanket", "Charging"],
  },
  {
    id: "b10",
    operator: "TNSTC",
    busNumber: "TN01-111",
    from: "Chennai",
    fromCode: "MAA",
    to: "Coimbatore",
    toCode: "CJB",
    depart: "20:00",
    arrive: "05:30",
    duration: "9h 30m",
    busType: "AC Sleeper",
    fare: 899,
    seatsAvailable: 20,
    amenities: ["Charging", "Water"],
  },
  {
    id: "b11",
    operator: "OSRTC",
    busNumber: "OD02-121",
    from: "Bhubaneswar",
    fromCode: "BBI",
    to: "Puri",
    toCode: "PURI",
    depart: "08:30",
    arrive: "10:00",
    duration: "1h 30m",
    busType: "AC Seater",
    fare: 249,
    seatsAvailable: 42,
    amenities: ["Charging"],
  },
  {
    id: "b12",
    operator: "WBSTC",
    busNumber: "WB03-131",
    from: "Kolkata",
    fromCode: "CCU",
    to: "Durgapur",
    toCode: "DGP",
    depart: "09:00",
    arrive: "12:30",
    duration: "3h 30m",
    busType: "Volvo AC",
    fare: 499,
    seatsAvailable: 26,
    amenities: ["Wi-Fi", "Charging"],
  },
  {
    id: "b13",
    operator: "Gujarat Travels",
    busNumber: "GJ04-141",
    from: "Ahmedabad",
    fromCode: "AMD",
    to: "Vadodara",
    toCode: "BDQ",
    depart: "07:45",
    arrive: "10:15",
    duration: "2h 30m",
    busType: "Volvo AC",
    fare: 399,
    seatsAvailable: 29,
    amenities: ["Charging", "Water"],
  },
  {
    id: "b14",
    operator: "GSRTC",
    busNumber: "GJ05-151",
    from: "Ahmedabad",
    fromCode: "AMD",
    to: "Rajkot",
    toCode: "RAJ",
    depart: "08:00",
    arrive: "13:00",
    duration: "5h",
    busType: "AC Seater",
    fare: 499,
    seatsAvailable: 32,
    amenities: ["Charging"],
  },
  {
    id: "b15",
    operator: "Punjab Roadways",
    busNumber: "PB06-161",
    from: "Delhi",
    fromCode: "DEL",
    to: "Amritsar",
    toCode: "ASR",
    depart: "21:00",
    arrive: "06:30",
    duration: "9h 30m",
    busType: "AC Sleeper",
    fare: 1199,
    seatsAvailable: 15,
    amenities: ["Blanket", "Charging"],
  },
  {
    id: "b16",
    operator: "JKSRTC",
    busNumber: "JK07-171",
    from: "Jammu",
    fromCode: "JMU",
    to: "Srinagar",
    toCode: "SXR",
    depart: "06:30",
    arrive: "14:00",
    duration: "7h 30m",
    busType: "AC Seater",
    fare: 799,
    seatsAvailable: 18,
    amenities: ["Water", "Charging"],
  },
  {
    id: "b17",
    operator: "UTC",
    busNumber: "UK08-181",
    from: "Delhi",
    fromCode: "DEL",
    to: "Dehradun",
    toCode: "DED",
    depart: "06:00",
    arrive: "11:00",
    duration: "5h",
    busType: "Volvo AC",
    fare: 699,
    seatsAvailable: 24,
    amenities: ["Wi-Fi", "Charging"],
  },
  {
    id: "b18",
    operator: "UTC",
    busNumber: "UK09-191",
    from: "Delhi",
    fromCode: "DEL",
    to: "Haridwar",
    toCode: "HW",
    depart: "07:00",
    arrive: "11:30",
    duration: "4h 30m",
    busType: "AC Seater",
    fare: 499,
    seatsAvailable: 30,
    amenities: ["Charging"],
  },
  {
    id: "b19",
    operator: "Bihar Roadways",
    busNumber: "BR10-201",
    from: "Patna",
    fromCode: "PAT",
    to: "Gaya",
    toCode: "GAY",
    depart: "08:00",
    arrive: "11:00",
    duration: "3h",
    busType: "AC Seater",
    fare: 349,
    seatsAvailable: 34,
    amenities: ["Water"],
  },
  {
    id: "b20",
    operator: "Bihar Roadways",
    busNumber: "BR10-211",
    from: "Patna",
    fromCode: "PAT",
    to: "Muzaffarpur",
    toCode: "MFP",
    depart: "09:00",
    arrive: "11:30",
    duration: "2h 30m",
    busType: "AC Seater",
    fare: 299,
    seatsAvailable: 38,
    amenities: ["Charging"],
  },
  {
    id: "b21",
    operator: "MP Roadways",
    busNumber: "MP11-221",
    from: "Bhopal",
    fromCode: "BHO",
    to: "Indore",
    toCode: "IDR",
    depart: "07:30",
    arrive: "12:00",
    duration: "4h 30m",
    busType: "Volvo AC",
    fare: 549,
    seatsAvailable: 27,
    amenities: ["Wi-Fi", "Charging"],
  },
  {
    id: "b22",
    operator: "HRTC",
    busNumber: "HP12-231",
    from: "Delhi",
    fromCode: "DEL",
    to: "Shimla",
    toCode: "SML",
    depart: "06:30",
    arrive: "14:30",
    duration: "8h",
    busType: "Volvo AC",
    fare: 899,
    seatsAvailable: 19,
    amenities: ["Wi-Fi", "Water"],
  },
  {
    id: "b23",
    operator: "HRTC",
    busNumber: "HP12-241",
    from: "Chandigarh",
    fromCode: "CDG",
    to: "Shimla",
    toCode: "SML",
    depart: "08:00",
    arrive: "12:00",
    duration: "4h",
    busType: "Volvo AC",
    fare: 599,
    seatsAvailable: 21,
    amenities: ["Charging"],
  },
  {
    id: "b24",
    operator: "KTCL",
    busNumber: "GA13-251",
    from: "Panaji",
    fromCode: "GOI",
    to: "Margao",
    toCode: "MAO",
    depart: "09:00",
    arrive: "10:30",
    duration: "1h 30m",
    busType: "AC Seater",
    fare: 249,
    seatsAvailable: 36,
    amenities: ["Charging"],
  },
  {
    id: "b25",
    operator: "KTCL",
    busNumber: "GA13-261",
    from: "Panaji",
    fromCode: "GOI",
    to: "Vasco",
    toCode: "VSG",
    depart: "10:00",
    arrive: "11:15",
    duration: "1h 15m",
    busType: "AC Seater",
    fare: 199,
    seatsAvailable: 41,
    amenities: ["Water"],
  },
  {
    id: "b26",
    operator: "Assam State Transport",
    busNumber: "AS14-271",
    from: "Guwahati",
    fromCode: "GHY",
    to: "Shillong",
    toCode: "SHL",
    depart: "07:00",
    arrive: "10:30",
    duration: "3h 30m",
    busType: "AC Seater",
    fare: 399,
    seatsAvailable: 25,
    amenities: ["Charging"],
  },
  {
    id: "b27",
    operator: "Jharkhand Travels",
    busNumber: "JH15-281",
    from: "Ranchi",
    fromCode: "RNC",
    to: "Jamshedpur",
    toCode: "IXW",
    depart: "08:00",
    arrive: "11:30",
    duration: "3h 30m",
    busType: "AC Seater",
    fare: 349,
    seatsAvailable: 31,
    amenities: ["Water"],
  },
  {
    id: "b28",
    operator: "Chhattisgarh Travels",
    busNumber: "CG16-291",
    from: "Raipur",
    fromCode: "RPR",
    to: "Bilaspur",
    toCode: "BSP",
    depart: "09:00",
    arrive: "12:00",
    duration: "3h",
    busType: "AC Seater",
    fare: 329,
    seatsAvailable: 33,
    amenities: ["Charging"],
  },
  {
    id: "b29",
    operator: "Kerala KSRTC",
    busNumber: "KL17-301",
    from: "Kochi",
    fromCode: "COK",
    to: "Thiruvananthapuram",
    toCode: "TRV",
    depart: "21:00",
    arrive: "05:30",
    duration: "8h 30m",
    busType: "AC Sleeper",
    fare: 999,
    seatsAvailable: 16,
    amenities: ["Blanket", "Charging"],
  },
  {
    id: "b30",
    operator: "TNSTC",
    busNumber: "TN18-311",
    from: "Chennai",
    fromCode: "MAA",
    to: "Madurai",
    toCode: "IXM",
    depart: "20:30",
    arrive: "06:00",
    duration: "9h 30m",
    busType: "AC Sleeper",
    fare: 949,
    seatsAvailable: 18,
    amenities: ["Blanket", "Water"],
  },
];

// ============================================================
// FLIGHT ROUTES
// ============================================================

export type FlightRoute = {
  id: string;
  airline: string;
  flightNumber: string;
  from: string;
  fromCode: string;
  to: string;
  toCode: string;
  depart: string;
  arrive: string;
  duration: string;
  stops: number;
  fare: number;
  seatsAvailable: number;
  cabin: "Economy" | "Premium Economy" | "Business";
};

export const flightRoutes: FlightRoute[] = [
  {
    id: "f1",
    airline: "Air India",
    flightNumber: "AI101",
    from: "Delhi",
    fromCode: "DEL",
    to: "Mumbai",
    toCode: "BOM",
    depart: "06:30",
    arrive: "08:40",
    duration: "2h 10m",
    stops: 0,
    fare: 5499,
    seatsAvailable: 42,
    cabin: "Economy",
  },
  {
    id: "f2",
    airline: "IndiGo",
    flightNumber: "6E201",
    from: "Delhi",
    fromCode: "DEL",
    to: "Bengaluru",
    toCode: "BLR",
    depart: "07:15",
    arrive: "10:00",
    duration: "2h 45m",
    stops: 0,
    fare: 5999,
    seatsAvailable: 37,
    cabin: "Economy",
  },
  {
    id: "f3",
    airline: "Vistara",
    flightNumber: "UK301",
    from: "Delhi",
    fromCode: "DEL",
    to: "Kolkata",
    toCode: "CCU",
    depart: "08:00",
    arrive: "10:15",
    duration: "2h 15m",
    stops: 0,
    fare: 6299,
    seatsAvailable: 24,
    cabin: "Economy",
  },
  {
    id: "f4",
    airline: "Air India",
    flightNumber: "AI401",
    from: "Delhi",
    fromCode: "DEL",
    to: "Chennai",
    toCode: "MAA",
    depart: "09:10",
    arrive: "11:55",
    duration: "2h 45m",
    stops: 0,
    fare: 6799,
    seatsAvailable: 29,
    cabin: "Economy",
  },
  {
    id: "f5",
    airline: "IndiGo",
    flightNumber: "6E501",
    from: "Delhi",
    fromCode: "DEL",
    to: "Hyderabad",
    toCode: "HYD",
    depart: "10:20",
    arrive: "12:30",
    duration: "2h 10m",
    stops: 0,
    fare: 5199,
    seatsAvailable: 46,
    cabin: "Economy",
  },
  {
    id: "f6",
    airline: "Akasa Air",
    flightNumber: "QP601",
    from: "Mumbai",
    fromCode: "BOM",
    to: "Ahmedabad",
    toCode: "AMD",
    depart: "07:00",
    arrive: "08:10",
    duration: "1h 10m",
    stops: 0,
    fare: 3299,
    seatsAvailable: 51,
    cabin: "Economy",
  },
  {
    id: "f7",
    airline: "IndiGo",
    flightNumber: "6E701",
    from: "Mumbai",
    fromCode: "BOM",
    to: "Goa",
    toCode: "GOI",
    depart: "08:30",
    arrive: "09:45",
    duration: "1h 15m",
    stops: 0,
    fare: 3599,
    seatsAvailable: 39,
    cabin: "Economy",
  },
  {
    id: "f8",
    airline: "Air India",
    flightNumber: "AI801",
    from: "Mumbai",
    fromCode: "BOM",
    to: "Kochi",
    toCode: "COK",
    depart: "10:00",
    arrive: "12:00",
    duration: "2h",
    stops: 0,
    fare: 4699,
    seatsAvailable: 32,
    cabin: "Economy",
  },
  {
    id: "f9",
    airline: "IndiGo",
    flightNumber: "6E901",
    from: "Bengaluru",
    fromCode: "BLR",
    to: "Chennai",
    toCode: "MAA",
    depart: "06:45",
    arrive: "07:45",
    duration: "1h",
    stops: 0,
    fare: 2999,
    seatsAvailable: 55,
    cabin: "Economy",
  },
  {
    id: "f10",
    airline: "Air India",
    flightNumber: "AI1001",
    from: "Bengaluru",
    fromCode: "BLR",
    to: "Delhi",
    toCode: "DEL",
    depart: "08:30",
    arrive: "11:20",
    duration: "2h 50m",
    stops: 0,
    fare: 5799,
    seatsAvailable: 34,
    cabin: "Economy",
  },
  {
    id: "f11",
    airline: "IndiGo",
    flightNumber: "6E1101",
    from: "Kolkata",
    fromCode: "CCU",
    to: "Delhi",
    toCode: "DEL",
    depart: "07:10",
    arrive: "09:35",
    duration: "2h 25m",
    stops: 0,
    fare: 5399,
    seatsAvailable: 44,
    cabin: "Economy",
  },
  {
    id: "f12",
    airline: "Air India",
    flightNumber: "AI1201",
    from: "Kolkata",
    fromCode: "CCU",
    to: "Mumbai",
    toCode: "BOM",
    depart: "09:30",
    arrive: "12:15",
    duration: "2h 45m",
    stops: 0,
    fare: 6299,
    seatsAvailable: 27,
    cabin: "Economy",
  },
  {
    id: "f13",
    airline: "IndiGo",
    flightNumber: "6E1301",
    from: "Hyderabad",
    fromCode: "HYD",
    to: "Delhi",
    toCode: "DEL",
    depart: "06:20",
    arrive: "08:40",
    duration: "2h 20m",
    stops: 0,
    fare: 4999,
    seatsAvailable: 41,
    cabin: "Economy",
  },
  {
    id: "f14",
    airline: "Akasa Air",
    flightNumber: "QP1401",
    from: "Hyderabad",
    fromCode: "HYD",
    to: "Mumbai",
    toCode: "BOM",
    depart: "08:45",
    arrive: "10:25",
    duration: "1h 40m",
    stops: 0,
    fare: 3799,
    seatsAvailable: 36,
    cabin: "Economy",
  },
  {
    id: "f15",
    airline: "IndiGo",
    flightNumber: "6E1501",
    from: "Chennai",
    fromCode: "MAA",
    to: "Delhi",
    toCode: "DEL",
    depart: "07:30",
    arrive: "10:20",
    duration: "2h 50m",
    stops: 0,
    fare: 5999,
    seatsAvailable: 31,
    cabin: "Economy",
  },
  {
    id: "f16",
    airline: "Air India",
    flightNumber: "AI1601",
    from: "Chennai",
    fromCode: "MAA",
    to: "Kolkata",
    toCode: "CCU",
    depart: "09:00",
    arrive: "11:25",
    duration: "2h 25m",
    stops: 0,
    fare: 4899,
    seatsAvailable: 28,
    cabin: "Economy",
  },
  {
    id: "f17",
    airline: "IndiGo",
    flightNumber: "6E1701",
    from: "Pune",
    fromCode: "PNQ",
    to: "Delhi",
    toCode: "DEL",
    depart: "06:50",
    arrive: "09:00",
    duration: "2h 10m",
    stops: 0,
    fare: 5199,
    seatsAvailable: 33,
    cabin: "Economy",
  },
  {
    id: "f18",
    airline: "Air India",
    flightNumber: "AI1801",
    from: "Pune",
    fromCode: "PNQ",
    to: "Bengaluru",
    toCode: "BLR",
    depart: "10:00",
    arrive: "11:25",
    duration: "1h 25m",
    stops: 0,
    fare: 3999,
    seatsAvailable: 26,
    cabin: "Economy",
  },
  {
    id: "f19",
    airline: "IndiGo",
    flightNumber: "6E1901",
    from: "Ahmedabad",
    fromCode: "AMD",
    to: "Delhi",
    toCode: "DEL",
    depart: "07:00",
    arrive: "08:35",
    duration: "1h 35m",
    stops: 0,
    fare: 3599,
    seatsAvailable: 48,
    cabin: "Economy",
  },
  {
    id: "f20",
    airline: "Air India",
    flightNumber: "AI2001",
    from: "Ahmedabad",
    fromCode: "AMD",
    to: "Mumbai",
    toCode: "BOM",
    depart: "09:00",
    arrive: "10:10",
    duration: "1h 10m",
    stops: 0,
    fare: 3199,
    seatsAvailable: 37,
    cabin: "Economy",
  },
  {
    id: "f21",
    airline: "IndiGo",
    flightNumber: "6E2101",
    from: "Jaipur",
    fromCode: "JAI",
    to: "Delhi",
    toCode: "DEL",
    depart: "06:40",
    arrive: "07:35",
    duration: "55m",
    stops: 0,
    fare: 2999,
    seatsAvailable: 44,
    cabin: "Economy",
  },
  {
    id: "f22",
    airline: "Air India",
    flightNumber: "AI2201",
    from: "Jaipur",
    fromCode: "JAI",
    to: "Mumbai",
    toCode: "BOM",
    depart: "09:20",
    arrive: "11:15",
    duration: "1h 55m",
    stops: 0,
    fare: 4499,
    seatsAvailable: 22,
    cabin: "Economy",
  },
  {
    id: "f23",
    airline: "IndiGo",
    flightNumber: "6E2301",
    from: "Lucknow",
    fromCode: "LKO",
    to: "Delhi",
    toCode: "DEL",
    depart: "07:15",
    arrive: "08:30",
    duration: "1h 15m",
    stops: 0,
    fare: 3299,
    seatsAvailable: 40,
    cabin: "Economy",
  },
  {
    id: "f24",
    airline: "Air India",
    flightNumber: "AI2401",
    from: "Lucknow",
    fromCode: "LKO",
    to: "Mumbai",
    toCode: "BOM",
    depart: "10:30",
    arrive: "12:35",
    duration: "2h 05m",
    stops: 0,
    fare: 4999,
    seatsAvailable: 19,
    cabin: "Economy",
  },
  {
    id: "f25",
    airline: "IndiGo",
    flightNumber: "6E2501",
    from: "Patna",
    fromCode: "PAT",
    to: "Delhi",
    toCode: "DEL",
    depart: "06:30",
    arrive: "08:20",
    duration: "1h 50m",
    stops: 0,
    fare: 3899,
    seatsAvailable: 36,
    cabin: "Economy",
  },
  {
    id: "f26",
    airline: "Air India",
    flightNumber: "AI2601",
    from: "Patna",
    fromCode: "PAT",
    to: "Kolkata",
    toCode: "CCU",
    depart: "09:30",
    arrive: "10:45",
    duration: "1h 15m",
    stops: 0,
    fare: 3299,
    seatsAvailable: 25,
    cabin: "Economy",
  },
  {
    id: "f27",
    airline: "IndiGo",
    flightNumber: "6E2701",
    from: "Goa",
    fromCode: "GOI",
    to: "Delhi",
    toCode: "DEL",
    depart: "08:00",
    arrive: "10:50",
    duration: "2h 50m",
    stops: 0,
    fare: 5299,
    seatsAvailable: 32,
    cabin: "Economy",
  },
  {
    id: "f28",
    airline: "Air India",
    flightNumber: "AI2801",
    from: "Kochi",
    fromCode: "COK",
    to: "Delhi",
    toCode: "DEL",
    depart: "07:45",
    arrive: "11:00",
    duration: "3h 15m",
    stops: 0,
    fare: 6499,
    seatsAvailable: 21,
    cabin: "Economy",
  },
  {
    id: "f29",
    airline: "IndiGo",
    flightNumber: "6E2901",
    from: "Guwahati",
    fromCode: "GAU",
    to: "Kolkata",
    toCode: "CCU",
    depart: "08:30",
    arrive: "09:40",
    duration: "1h 10m",
    stops: 0,
    fare: 3499,
    seatsAvailable: 35,
    cabin: "Economy",
  },
  {
    id: "f30",
    airline: "Air India",
    flightNumber: "AI3001",
    from: "Delhi",
    fromCode: "DEL",
    to: "Srinagar",
    toCode: "SXR",
    depart: "06:15",
    arrive: "07:45",
    duration: "1h 30m",
    stops: 0,
    fare: 4299,
    seatsAvailable: 29,
    cabin: "Economy",
  },
];

// ============================================================
// FERRY ROUTES
// ============================================================

export type FerryRoute = {
  id: string;
  operator: string;
  ferryName: string;
  from: string;
  fromCode: string;
  to: string;
  toCode: string;
  depart: string;
  arrive: string;
  duration: string;
  fare: number;
  seatsAvailable: number;
  ferryType: "High Speed" | "Passenger Ferry" | "Catamaran";
};

export const ferryRoutes: FerryRoute[] = [
  {
    id: "fy1",
    operator: "Mumbai Waterways",
    ferryName: "Harbour Express",
    from: "Gateway of India",
    fromCode: "GOI",
    to: "Mandwa",
    toCode: "MND",
    depart: "08:00",
    arrive: "08:45",
    duration: "45m",
    fare: 450,
    seatsAvailable: 82,
    ferryType: "High Speed",
  },
  {
    id: "fy2",
    operator: "Mumbai Waterways",
    ferryName: "SeaLink Ferry",
    from: "Gateway of India",
    fromCode: "GOI",
    to: "Alibaug",
    toCode: "ALB",
    depart: "09:30",
    arrive: "10:30",
    duration: "1h",
    fare: 650,
    seatsAvailable: 61,
    ferryType: "Catamaran",
  },
  {
    id: "fy3",
    operator: "Goa Ferries",
    ferryName: "River Cruiser",
    from: "Panaji",
    fromCode: "PNJ",
    to: "Betim",
    toCode: "BTM",
    depart: "08:15",
    arrive: "08:35",
    duration: "20m",
    fare: 80,
    seatsAvailable: 120,
    ferryType: "Passenger Ferry",
  },
  {
    id: "fy4",
    operator: "Goa Ferries",
    ferryName: "Mandovi Express",
    from: "Panaji",
    fromCode: "PNJ",
    to: "Chorao",
    toCode: "CHO",
    depart: "10:00",
    arrive: "10:25",
    duration: "25m",
    fare: 100,
    seatsAvailable: 100,
    ferryType: "Passenger Ferry",
  },
  {
    id: "fy5",
    operator: "Kerala Waterways",
    ferryName: "Kochi Fast",
    from: "Fort Kochi",
    fromCode: "FKO",
    to: "Vypin",
    toCode: "VYP",
    depart: "07:30",
    arrive: "07:50",
    duration: "20m",
    fare: 60,
    seatsAvailable: 140,
    ferryType: "Passenger Ferry",
  },
  {
    id: "fy6",
    operator: "Kerala Waterways",
    ferryName: "Marine Express",
    from: "Ernakulam",
    fromCode: "ERS",
    to: "Fort Kochi",
    toCode: "FKO",
    depart: "08:00",
    arrive: "08:30",
    duration: "30m",
    fare: 90,
    seatsAvailable: 110,
    ferryType: "High Speed",
  },
  {
    id: "fy7",
    operator: "Andaman Ferries",
    ferryName: "Island Runner",
    from: "Port Blair",
    fromCode: "IXZ",
    to: "Havelock",
    toCode: "HAV",
    depart: "08:00",
    arrive: "10:30",
    duration: "2h 30m",
    fare: 1450,
    seatsAvailable: 74,
    ferryType: "High Speed",
  },
  {
    id: "fy8",
    operator: "Andaman Ferries",
    ferryName: "Island Cruiser",
    from: "Port Blair",
    fromCode: "IXZ",
    to: "Neil Island",
    toCode: "NEI",
    depart: "09:30",
    arrive: "11:45",
    duration: "2h 15m",
    fare: 1250,
    seatsAvailable: 68,
    ferryType: "Catamaran",
  },
  {
    id: "fy9",
    operator: "Andaman Ferries",
    ferryName: "Havelock Express",
    from: "Havelock",
    fromCode: "HAV",
    to: "Neil Island",
    toCode: "NEI",
    depart: "13:00",
    arrive: "14:00",
    duration: "1h",
    fare: 950,
    seatsAvailable: 56,
    ferryType: "High Speed",
  },
  {
    id: "fy10",
    operator: "Lakshadweep Marine",
    ferryName: "Coral Runner",
    from: "Kochi",
    fromCode: "COK",
    to: "Kavaratti",
    toCode: "KVT",
    depart: "07:00",
    arrive: "15:00",
    duration: "8h",
    fare: 2250,
    seatsAvailable: 91,
    ferryType: "High Speed",
  },
  {
    id: "fy11",
    operator: "Lakshadweep Marine",
    ferryName: "Island Pearl",
    from: "Kavaratti",
    fromCode: "KVT",
    to: "Agatti",
    toCode: "AGT",
    depart: "09:00",
    arrive: "11:00",
    duration: "2h",
    fare: 1100,
    seatsAvailable: 48,
    ferryType: "Catamaran",
  },
  {
    id: "fy12",
    operator: "Mumbai Waterways",
    ferryName: "Elephanta Express",
    from: "Gateway of India",
    fromCode: "GOI",
    to: "Elephanta Island",
    toCode: "ELE",
    depart: "09:00",
    arrive: "10:00",
    duration: "1h",
    fare: 550,
    seatsAvailable: 90,
    ferryType: "Passenger Ferry",
  },
  {
    id: "fy13",
    operator: "Mumbai Waterways",
    ferryName: "Alibaug Runner",
    from: "Mandwa",
    fromCode: "MND",
    to: "Mumbai",
    toCode: "BOM",
    depart: "17:00",
    arrive: "17:45",
    duration: "45m",
    fare: 450,
    seatsAvailable: 72,
    ferryType: "High Speed",
  },
  {
    id: "fy14",
    operator: "Goa Ferries",
    ferryName: "Divar Ferry",
    from: "Ribandar",
    fromCode: "RIB",
    to: "Divar Island",
    toCode: "DIV",
    depart: "08:30",
    arrive: "08:50",
    duration: "20m",
    fare: 70,
    seatsAvailable: 115,
    ferryType: "Passenger Ferry",
  },
  {
    id: "fy15",
    operator: "Kerala Waterways",
    ferryName: "Vembanad Cruiser",
    from: "Alappuzha",
    fromCode: "ALL",
    to: "Kuttanad",
    toCode: "KUT",
    depart: "09:00",
    arrive: "10:30",
    duration: "1h 30m",
    fare: 250,
    seatsAvailable: 88,
    ferryType: "Passenger Ferry",
  },
  {
    id: "fy16",
    operator: "Kerala Waterways",
    ferryName: "Backwater Express",
    from: "Alappuzha",
    fromCode: "ALL",
    to: "Kumarakom",
    toCode: "KUM",
    depart: "11:00",
    arrive: "12:15",
    duration: "1h 15m",
    fare: 300,
    seatsAvailable: 79,
    ferryType: "Catamaran",
  },
  {
    id: "fy17",
    operator: "Kerala Waterways",
    ferryName: "Kollam Cruiser",
    from: "Kollam",
    fromCode: "QLN",
    to: "Alappuzha",
    toCode: "ALL",
    depart: "07:00",
    arrive: "10:00",
    duration: "3h",
    fare: 550,
    seatsAvailable: 65,
    ferryType: "Passenger Ferry",
  },
  {
    id: "fy18",
    operator: "Kerala Waterways",
    ferryName: "Kochi Island Express",
    from: "Ernakulam",
    fromCode: "ERS",
    to: "Willington Island",
    toCode: "WIL",
    depart: "08:30",
    arrive: "08:50",
    duration: "20m",
    fare: 70,
    seatsAvailable: 130,
    ferryType: "Passenger Ferry",
  },
  {
    id: "fy19",
    operator: "Andaman Ferries",
    ferryName: "Ross Island Ferry",
    from: "Port Blair",
    fromCode: "IXZ",
    to: "Ross Island",
    toCode: "ROS",
    depart: "10:00",
    arrive: "10:30",
    duration: "30m",
    fare: 650,
    seatsAvailable: 84,
    ferryType: "Passenger Ferry",
  },
  {
    id: "fy20",
    operator: "Andaman Ferries",
    ferryName: "North Bay Express",
    from: "Port Blair",
    fromCode: "IXZ",
    to: "North Bay",
    toCode: "NBY",
    depart: "11:00",
    arrive: "11:40",
    duration: "40m",
    fare: 750,
    seatsAvailable: 73,
    ferryType: "High Speed",
  },
  {
    id: "fy21",
    operator: "Andaman Ferries",
    ferryName: "Havelock Sunset",
    from: "Havelock",
    fromCode: "HAV",
    to: "Port Blair",
    toCode: "IXZ",
    depart: "16:00",
    arrive: "18:30",
    duration: "2h 30m",
    fare: 1450,
    seatsAvailable: 59,
    ferryType: "High Speed",
  },
  {
    id: "fy22",
    operator: "Lakshadweep Marine",
    ferryName: "Coral Express",
    from: "Agatti",
    fromCode: "AGT",
    to: "Kavaratti",
    toCode: "KVT",
    depart: "12:00",
    arrive: "14:00",
    duration: "2h",
    fare: 1100,
    seatsAvailable: 44,
    ferryType: "Catamaran",
  },
  {
    id: "fy23",
    operator: "Lakshadweep Marine",
    ferryName: "Island Voyager",
    from: "Kochi",
    fromCode: "COK",
    to: "Agatti",
    toCode: "AGT",
    depart: "06:30",
    arrive: "14:30",
    duration: "8h",
    fare: 2300,
    seatsAvailable: 80,
    ferryType: "High Speed",
  },
  {
    id: "fy24",
    operator: "Goa Ferries",
    ferryName: "Mandovi Local",
    from: "Panaji",
    fromCode: "PNJ",
    to: "Betim",
    toCode: "BTM",
    depart: "14:00",
    arrive: "14:20",
    duration: "20m",
    fare: 80,
    seatsAvailable: 126,
    ferryType: "Passenger Ferry",
  },
  {
    id: "fy25",
    operator: "Goa Ferries",
    ferryName: "Chorao Cruiser",
    from: "Chorao",
    fromCode: "CHO",
    to: "Ribandar",
    toCode: "RIB",
    depart: "15:00",
    arrive: "15:25",
    duration: "25m",
    fare: 100,
    seatsAvailable: 96,
    ferryType: "Passenger Ferry",
  },
  {
    id: "fy26",
    operator: "Mumbai Waterways",
    ferryName: "Mandwa Star",
    from: "Mumbai",
    fromCode: "BOM",
    to: "Mandwa",
    toCode: "MND",
    depart: "07:30",
    arrive: "08:15",
    duration: "45m",
    fare: 450,
    seatsAvailable: 77,
    ferryType: "High Speed",
  },
  {
    id: "fy27",
    operator: "Mumbai Waterways",
    ferryName: "Elephanta Star",
    from: "Gateway of India",
    fromCode: "GOI",
    to: "Elephanta Island",
    toCode: "ELE",
    depart: "12:00",
    arrive: "13:00",
    duration: "1h",
    fare: 550,
    seatsAvailable: 83,
    ferryType: "Passenger Ferry",
  },
  {
    id: "fy28",
    operator: "Kerala Waterways",
    ferryName: "Vypin Express",
    from: "Vypin",
    fromCode: "VYP",
    to: "Fort Kochi",
    toCode: "FKO",
    depart: "17:00",
    arrive: "17:20",
    duration: "20m",
    fare: 60,
    seatsAvailable: 135,
    ferryType: "Passenger Ferry",
  },
  {
    id: "fy29",
    operator: "Kerala Waterways",
    ferryName: "Kumarakom Express",
    from: "Kumarakom",
    fromCode: "KUM",
    to: "Alappuzha",
    toCode: "ALL",
    depart: "16:00",
    arrive: "17:15",
    duration: "1h 15m",
    fare: 300,
    seatsAvailable: 74,
    ferryType: "Catamaran",
  },
  {
    id: "fy30",
    operator: "Andaman Ferries",
    ferryName: "Neil Star",
    from: "Neil Island",
    fromCode: "NEI",
    to: "Havelock",
    toCode: "HAV",
    depart: "15:00",
    arrive: "16:00",
    duration: "1h",
    fare: 950,
    seatsAvailable: 51,
    ferryType: "High Speed",
  },
];

// ============================================================
// METRO ROUTES
// NOTE: Completely separate from train routes.
// ============================================================

export type MetroRoute = {
  id: string;
  metro: string;
  line: string;
  from: string;
  fromCode: string;
  to: string;
  toCode: string;
  duration: string;
  fare: number;
  frequency: string;
  interchanges: number;
};

export const metroRoutes: MetroRoute[] = [
  {
    id: "m1",
    metro: "Delhi Metro",
    line: "Yellow Line",
    from: "Samaypur Badli",
    fromCode: "SPB",
    to: "HUDA City Centre",
    toCode: "HCC",
    duration: "52m",
    fare: 40,
    frequency: "3-5 min",
    interchanges: 0,
  },
  {
    id: "m2",
    metro: "Delhi Metro",
    line: "Blue Line",
    from: "Dwarka Sector 21",
    fromCode: "DS21",
    to: "Noida Electronic City",
    toCode: "NEC",
    duration: "65m",
    fare: 60,
    frequency: "3-5 min",
    interchanges: 0,
  },
  {
    id: "m3",
    metro: "Delhi Metro",
    line: "Red Line",
    from: "Rithala",
    fromCode: "RIT",
    to: "Shaheed Sthal",
    toCode: "SHS",
    duration: "48m",
    fare: 40,
    frequency: "4-6 min",
    interchanges: 0,
  },
  {
    id: "m4",
    metro: "Delhi Metro",
    line: "Violet Line",
    from: "Kashmere Gate",
    fromCode: "KMG",
    to: "Raja Nahar Singh",
    toCode: "RNS",
    duration: "58m",
    fare: 50,
    frequency: "4-6 min",
    interchanges: 0,
  },
  {
    id: "m5",
    metro: "Delhi Metro",
    line: "Magenta Line",
    from: "Janakpuri West",
    fromCode: "JPW",
    to: "Botanical Garden",
    toCode: "BTG",
    duration: "43m",
    fare: 50,
    frequency: "4-6 min",
    interchanges: 0,
  },
  {
    id: "m6",
    metro: "Delhi Metro",
    line: "Pink Line",
    from: "Majlis Park",
    fromCode: "MPK",
    to: "Shiv Vihar",
    toCode: "SHV",
    duration: "58m",
    fare: 50,
    frequency: "4-6 min",
    interchanges: 0,
  },
  {
    id: "m7",
    metro: "Delhi Metro",
    line: "Airport Express",
    from: "New Delhi Metro",
    fromCode: "NDM",
    to: "Dwarka Sector 21",
    toCode: "DS21",
    duration: "23m",
    fare: 60,
    frequency: "5-10 min",
    interchanges: 0,
  },
  {
    id: "m8",
    metro: "Delhi Metro",
    line: "Blue Line",
    from: "Rajiv Chowk",
    fromCode: "RJC",
    to: "Akshardham",
    toCode: "AKS",
    duration: "12m",
    fare: 30,
    frequency: "3-5 min",
    interchanges: 0,
  },
  {
    id: "m9",
    metro: "Delhi Metro",
    line: "Yellow Line",
    from: "Rajiv Chowk",
    fromCode: "RJC",
    to: "Chandni Chowk",
    toCode: "CCK",
    duration: "7m",
    fare: 20,
    frequency: "3-5 min",
    interchanges: 0,
  },
  {
    id: "m10",
    metro: "Delhi Metro",
    line: "Yellow Line",
    from: "Rajiv Chowk",
    fromCode: "RJC",
    to: "Saket",
    toCode: "SKT",
    duration: "24m",
    fare: 30,
    frequency: "3-5 min",
    interchanges: 0,
  },
  {
    id: "m11",
    metro: "Mumbai Metro",
    line: "Line 1",
    from: "Versova",
    fromCode: "VER",
    to: "Ghatkopar",
    toCode: "GHA",
    duration: "42m",
    fare: 40,
    frequency: "4-6 min",
    interchanges: 0,
  },
  {
    id: "m12",
    metro: "Mumbai Metro",
    line: "Line 2A",
    from: "Dahisar East",
    fromCode: "DHE",
    to: "Andheri West",
    toCode: "AW",
    duration: "38m",
    fare: 30,
    frequency: "5-7 min",
    interchanges: 0,
  },
  {
    id: "m13",
    metro: "Mumbai Metro",
    line: "Line 7",
    from: "Dahisar East",
    fromCode: "DHE",
    to: "Aarey",
    toCode: "ARY",
    duration: "35m",
    fare: 30,
    frequency: "5-7 min",
    interchanges: 0,
  },
  {
    id: "m14",
    metro: "Bengaluru Metro",
    line: "Purple Line",
    from: "Whitefield",
    fromCode: "WFD",
    to: "Challaghatta",
    toCode: "CHG",
    duration: "54m",
    fare: 50,
    frequency: "4-6 min",
    interchanges: 0,
  },
  {
    id: "m15",
    metro: "Bengaluru Metro",
    line: "Green Line",
    from: "Nagasandra",
    fromCode: "NGS",
    to: "Silk Institute",
    toCode: "SI",
    duration: "56m",
    fare: 50,
    frequency: "4-6 min",
    interchanges: 0,
  },
  {
    id: "m16",
    metro: "Chennai Metro",
    line: "Blue Line",
    from: "Airport",
    fromCode: "AIR",
    to: "Washermenpet",
    toCode: "WPT",
    duration: "35m",
    fare: 40,
    frequency: "5-7 min",
    interchanges: 0,
  },
  {
    id: "m17",
    metro: "Chennai Metro",
    line: "Green Line",
    from: "St Thomas Mount",
    fromCode: "STM",
    to: "Central",
    toCode: "CEN",
    duration: "29m",
    fare: 30,
    frequency: "5-7 min",
    interchanges: 0,
  },
  {
    id: "m18",
    metro: "Hyderabad Metro",
    line: "Red Line",
    from: "Miyapur",
    fromCode: "MYP",
    to: "LB Nagar",
    toCode: "LBN",
    duration: "52m",
    fare: 50,
    frequency: "4-6 min",
    interchanges: 0,
  },
  {
    id: "m19",
    metro: "Hyderabad Metro",
    line: "Blue Line",
    from: "Nagole",
    fromCode: "NGL",
    to: "Raidurg",
    toCode: "RDG",
    duration: "45m",
    fare: 50,
    frequency: "4-6 min",
    interchanges: 0,
  },
  {
    id: "m20",
    metro: "Kolkata Metro",
    line: "Blue Line",
    from: "Noapara",
    fromCode: "NPR",
    to: "Kavi Subhash",
    toCode: "KVS",
    duration: "43m",
    fare: 30,
    frequency: "5-7 min",
    interchanges: 0,
  },
  {
    id: "m21",
    metro: "Kolkata Metro",
    line: "Green Line",
    from: "Howrah Maidan",
    fromCode: "HWM",
    to: "Salt Lake Sector V",
    toCode: "SLV",
    duration: "35m",
    fare: 30,
    frequency: "5-7 min",
    interchanges: 0,
  },
  {
    id: "m22",
    metro: "Ahmedabad Metro",
    line: "North-South",
    from: "Motera Stadium",
    fromCode: "MOT",
    to: "Vastral Gam",
    toCode: "VAG",
    duration: "48m",
    fare: 40,
    frequency: "6-8 min",
    interchanges: 0,
  },
  {
    id: "m23",
    metro: "Lucknow Metro",
    line: "North-South",
    from: "Munshipulia",
    fromCode: "MNP",
    to: "CCS Airport",
    toCode: "AIR",
    duration: "42m",
    fare: 40,
    frequency: "5-8 min",
    interchanges: 0,
  },
  {
    id: "m24",
    metro: "Jaipur Metro",
    line: "Pink Line",
    from: "Mansarovar",
    fromCode: "MSR",
    to: "Badi Chaupar",
    toCode: "BCP",
    duration: "31m",
    fare: 30,
    frequency: "6-8 min",
    interchanges: 0,
  },
  {
    id: "m25",
    metro: "Kochi Metro",
    line: "Aluva Line",
    from: "Aluva",
    fromCode: "ALV",
    to: "Tripunithura",
    toCode: "TPR",
    duration: "45m",
    fare: 50,
    frequency: "5-7 min",
    interchanges: 0,
  },
  {
    id: "m26",
    metro: "Nagpur Metro",
    line: "Aqua Line",
    from: "Sitabuldi",
    fromCode: "SIT",
    to: "Lokmanya Nagar",
    toCode: "LMN",
    duration: "34m",
    fare: 30,
    frequency: "6-8 min",
    interchanges: 0,
  },
  {
    id: "m27",
    metro: "Nagpur Metro",
    line: "Orange Line",
    from: "Automotive Square",
    fromCode: "ASQ",
    to: "Khapri",
    toCode: "KHP",
    duration: "39m",
    fare: 40,
    frequency: "6-8 min",
    interchanges: 0,
  },
  {
    id: "m28",
    metro: "Pune Metro",
    line: "Aqua Line",
    from: "Vanaz",
    fromCode: "VNZ",
    to: "Ramwadi",
    toCode: "RMW",
    duration: "29m",
    fare: 30,
    frequency: "5-8 min",
    interchanges: 0,
  },
  {
    id: "m29",
    metro: "Pune Metro",
    line: "Purple Line",
    from: "PCMC",
    fromCode: "PCM",
    to: "Swargate",
    toCode: "SWG",
    duration: "34m",
    fare: 30,
    frequency: "5-8 min",
    interchanges: 0,
  },
  {
    id: "m30",
    metro: "Delhi Metro",
    line: "Green Line",
    from: "Inderlok",
    fromCode: "IND",
    to: "Brigadier Hoshiar Singh",
    toCode: "BHS",
    duration: "38m",
    fare: 40,
    frequency: "5-7 min",
    interchanges: 0,
  },
];

// ============================================================
// HOTEL
// IMPORTANT:
// NO from/to fields.
// 50 DESTINATIONS × 4 HOTELS = 200 HOTELS
// ============================================================

export type Hotel = {
  id: string;
  name: string;
  city: string;
  state: string;
  area: string;
  rating: number;
  reviews: number;
  pricePerNight: number;
  originalPrice?: number;
  image?: string;
  amenities: string[];
  tags?: string[];
  roomType: string;
  refundable: boolean;
  breakfastIncluded: boolean;
};

const hotelDestinations = [
  ["New Delhi", "Delhi", "Connaught Place"],
  ["Mumbai", "Maharashtra", "Andheri"],
  ["Bengaluru", "Karnataka", "Whitefield"],
  ["Chennai", "Tamil Nadu", "T Nagar"],
  ["Hyderabad", "Telangana", "Banjara Hills"],
  ["Kolkata", "West Bengal", "Park Street"],
  ["Jaipur", "Rajasthan", "MI Road"],
  ["Ahmedabad", "Gujarat", "Navrangpura"],
  ["Pune", "Maharashtra", "Hinjewadi"],
  ["Lucknow", "Uttar Pradesh", "Gomti Nagar"],
  ["Agra", "Uttar Pradesh", "Taj Ganj"],
  ["Varanasi", "Uttar Pradesh", "Cantonment"],
  ["Amritsar", "Punjab", "Golden Temple Area"],
  ["Chandigarh", "Chandigarh", "Sector 17"],
  ["Goa", "Goa", "Calangute"],
  ["Kochi", "Kerala", "Fort Kochi"],
  ["Thiruvananthapuram", "Kerala", "Kowdiar"],
  ["Coimbatore", "Tamil Nadu", "RS Puram"],
  ["Madurai", "Tamil Nadu", "KK Nagar"],
  ["Mysuru", "Karnataka", "City Centre"],
  ["Bhopal", "Madhya Pradesh", "MP Nagar"],
  ["Indore", "Madhya Pradesh", "Vijay Nagar"],
  ["Nagpur", "Maharashtra", "Dharampeth"],
  ["Surat", "Gujarat", "Athwa"],
  ["Vadodara", "Gujarat", "Alkapuri"],
  ["Rajkot", "Gujarat", "Kalawad Road"],
  ["Udaipur", "Rajasthan", "Lake Pichola"],
  ["Jodhpur", "Rajasthan", "Ratanada"],
  ["Ajmer", "Rajasthan", "Civil Lines"],
  ["Kota", "Rajasthan", "Talwandi"],
  ["Patna", "Bihar", "Fraser Road"],
  ["Gaya", "Bihar", "Gaya Town"],
  ["Ranchi", "Jharkhand", "Main Road"],
  ["Jamshedpur", "Jharkhand", "Bistupur"],
  ["Bhubaneswar", "Odisha", "Jaydev Vihar"],
  ["Puri", "Odisha", "Swargadwar"],
  ["Guwahati", "Assam", "Paltan Bazaar"],
  ["Shimla", "Himachal Pradesh", "Mall Road"],
  ["Manali", "Himachal Pradesh", "Old Manali"],
  ["Dehradun", "Uttarakhand", "Rajpur Road"],
  ["Haridwar", "Uttarakhand", "Har Ki Pauri"],
  ["Srinagar", "Jammu & Kashmir", "Dal Lake"],
  ["Jammu", "Jammu & Kashmir", "Residency Road"],
  ["Visakhapatnam", "Andhra Pradesh", "Beach Road"],
  ["Vijayawada", "Andhra Pradesh", "Benz Circle"],
  ["Tirupati", "Andhra Pradesh", "Temple Area"],
  ["Mangaluru", "Karnataka", "Hampankatta"],
  ["Pondicherry", "Puducherry", "White Town"],
  ["Rishikesh", "Uttarakhand", "Tapovan"],
  ["Andaman", "Andaman & Nicobar", "Port Blair"],
] as const;

const hotelNames = [
  "Grand",
  "Royal",
  "City",
  "Central",
];

const hotelRoomTypes = [
  "Deluxe Room",
  "Premium Room",
  "Executive Room",
  "Family Room",
];

const hotelAmenities = [
  ["Free Wi-Fi", "Breakfast", "Parking"],
  ["Free Wi-Fi", "Swimming Pool", "Restaurant"],
  ["Free Wi-Fi", "Gym", "24×7 Reception"],
  ["Free Wi-Fi", "Breakfast", "Room Service"],
];

export const hotels: Hotel[] = hotelDestinations.flatMap(
  ([city, state, area], destinationIndex) =>
    hotelNames.map((prefix, hotelIndex) => {
      const basePrice =
        2499 +
        destinationIndex * 55 +
        hotelIndex * 450;

      return {
        id: `h${destinationIndex + 1}-${hotelIndex + 1}`,
        name: `${prefix} ${city} Hotel`,
        city,
        state,
        area,
        rating: Number((4.1 + ((destinationIndex + hotelIndex) % 6) * 0.1).toFixed(1)),
        reviews: 850 + destinationIndex * 97 + hotelIndex * 183,
        pricePerNight: basePrice,
        originalPrice: basePrice + 900,
        image: `/hotel-${(hotelIndex % 4) + 1}.jpg`,
        amenities: hotelAmenities[hotelIndex],
        tags:
          hotelIndex === 0
            ? ["Popular", "Best value"]
            : hotelIndex === 1
              ? ["Highly rated"]
              : hotelIndex === 2
                ? ["Near attractions"]
                : ["Family friendly"],
        roomType: hotelRoomTypes[hotelIndex],
        refundable: hotelIndex !== 3,
        breakfastIncluded: hotelIndex === 0 || hotelIndex === 3,
      };
    }),
);

// ============================================================
// PASSENGERS
// ============================================================

export type Passenger = {
  id: string;
  name: string;
  age: number;
  gender: "M" | "F" | "O";
  berth:
    | "Lower"
    | "Middle"
    | "Upper"
    | "Side Lower"
    | "Side Upper"
    | "No Preference";
  idType: string;
  idNumber: string;
};

export const savedPassengers: Passenger[] = [
  {
    id: "p1",
    name: "Aarav Sharma",
    age: 32,
    gender: "M",
    berth: "Lower",
    idType: "Aadhaar",
    idNumber: "XXXX-1234",
  },
  {
    id: "p2",
    name: "Priya Iyer",
    age: 29,
    gender: "F",
    berth: "Side Lower",
    idType: "Aadhaar",
    idNumber: "XXXX-5581",
  },
  {
    id: "p3",
    name: "Rohan Mehta",
    age: 8,
    gender: "M",
    berth: "No Preference",
    idType: "Birth Cert.",
    idNumber: "BC-2017-9921",
  },
  {
    id: "p4",
    name: "Ananya Rao",
    age: 67,
    gender: "F",
    berth: "Lower",
    idType: "Sr. Citizen",
    idNumber: "SC-1958-7712",
  },
];

// ============================================================
// STATIONS
// ============================================================

export type Station = {
  name: string;
  code: string;
  city: string;
  state: string;
};

export const stations: Station[] = [
  { name: "New Delhi", code: "NDLS", city: "Delhi", state: "Delhi" },
  { name: "Old Delhi", code: "DLI", city: "Delhi", state: "Delhi" },
  { name: "Hazrat Nizamuddin", code: "NZM", city: "Delhi", state: "Delhi" },
  { name: "Delhi Sarai Rohilla", code: "DEE", city: "Delhi", state: "Delhi" },
  { name: "Anand Vihar Terminal", code: "ANVT", city: "Delhi", state: "Delhi" },

  { name: "Mumbai Central", code: "MMCT", city: "Mumbai", state: "Maharashtra" },
  { name: "CSMT", code: "CSMT", city: "Mumbai", state: "Maharashtra" },
  { name: "Bandra Terminus", code: "BDTS", city: "Mumbai", state: "Maharashtra" },

  { name: "Pune Junction", code: "PUNE", city: "Pune", state: "Maharashtra" },
  { name: "Nagpur Junction", code: "NGP", city: "Nagpur", state: "Maharashtra" },

  { name: "KSR Bengaluru City", code: "SBC", city: "Bengaluru", state: "Karnataka" },
  { name: "Yesvantpur Junction", code: "YPR", city: "Bengaluru", state: "Karnataka" },

  { name: "MGR Chennai Central", code: "MAS", city: "Chennai", state: "Tamil Nadu" },
  { name: "Chennai Egmore", code: "MS", city: "Chennai", state: "Tamil Nadu" },

  { name: "Howrah Junction", code: "HWH", city: "Kolkata", state: "West Bengal" },
  { name: "Sealdah", code: "SDAH", city: "Kolkata", state: "West Bengal" },

  { name: "Secunderabad Junction", code: "SC", city: "Hyderabad", state: "Telangana" },
  { name: "Hyderabad Deccan", code: "HYB", city: "Hyderabad", state: "Telangana" },

  { name: "Ahmedabad Junction", code: "ADI", city: "Ahmedabad", state: "Gujarat" },
  { name: "Surat", code: "ST", city: "Surat", state: "Gujarat" },
  { name: "Vadodara Junction", code: "BRC", city: "Vadodara", state: "Gujarat" },

  { name: "Jaipur Junction", code: "JP", city: "Jaipur", state: "Rajasthan" },
  { name: "Jodhpur Junction", code: "JU", city: "Jodhpur", state: "Rajasthan" },
  { name: "Udaipur City", code: "UDZ", city: "Udaipur", state: "Rajasthan" },
  { name: "Ajmer Junction", code: "AII", city: "Ajmer", state: "Rajasthan" },

  { name: "Lucknow NR", code: "LKO", city: "Lucknow", state: "Uttar Pradesh" },
  { name: "Kanpur Central", code: "CNB", city: "Kanpur", state: "Uttar Pradesh" },
  { name: "Varanasi Junction", code: "BSB", city: "Varanasi", state: "Uttar Pradesh" },
  { name: "Agra Cantt", code: "AGC", city: "Agra", state: "Uttar Pradesh" },

  { name: "Patna Junction", code: "PNBE", city: "Patna", state: "Bihar" },
  { name: "Gaya Junction", code: "GAYA", city: "Gaya", state: "Bihar" },

  { name: "Bhubaneswar", code: "BBS", city: "Bhubaneswar", state: "Odisha" },
  { name: "Puri", code: "PURI", city: "Puri", state: "Odisha" },

  { name: "Bhopal Junction", code: "BPL", city: "Bhopal", state: "Madhya Pradesh" },
  { name: "Indore Junction", code: "INDB", city: "Indore", state: "Madhya Pradesh" },

  { name: "Chandigarh", code: "CDG", city: "Chandigarh", state: "Chandigarh" },
  { name: "Amritsar Junction", code: "ASR", city: "Amritsar", state: "Punjab" },

  { name: "Dehradun", code: "DDN", city: "Dehradun", state: "Uttarakhand" },
  { name: "Haridwar Junction", code: "HW", city: "Haridwar", state: "Uttarakhand" },

  { name: "Jammu Tawi", code: "JAT", city: "Jammu", state: "Jammu & Kashmir" },
  { name: "Srinagar", code: "SINA", city: "Srinagar", state: "Jammu & Kashmir" },

  { name: "Shimla", code: "SML", city: "Shimla", state: "Himachal Pradesh" },

  { name: "Guwahati", code: "GHY", city: "Guwahati", state: "Assam" },
  { name: "Dibrugarh", code: "DBRG", city: "Dibrugarh", state: "Assam" },

  { name: "Ranchi Junction", code: "RNC", city: "Ranchi", state: "Jharkhand" },
  { name: "Dhanbad Junction", code: "DHN", city: "Dhanbad", state: "Jharkhand" },

  { name: "Raipur Junction", code: "R", city: "Raipur", state: "Chhattisgarh" },
  { name: "Bilaspur Junction", code: "BSP", city: "Bilaspur", state: "Chhattisgarh" },

  { name: "Madgaon", code: "MAO", city: "Madgaon", state: "Goa" },
  { name: "Vasco Da Gama", code: "VSG", city: "Vasco", state: "Goa" },
];

// ============================================================
// SEARCH SUGGESTIONS
// ============================================================

export const suggestions = [
  "Cheapest AC train from Delhi to Jaipur tomorrow morning",
  "Vande Bharat from Mumbai to Ahmedabad this Friday",
  "Overnight sleeper from Bengaluru to Chennai",
  "Fastest train Delhi to Lucknow under ₹1500",
  "Tatkal 3A from Patna to Howrah for Monday",
  "Volvo bus from Delhi to Jaipur tonight",
  "Flight from Delhi to Mumbai tomorrow morning",
  "Ferry from Mumbai to Mandwa this weekend",
  "Delhi Metro from Rajiv Chowk to Saket",
  "Hotel near Connaught Place under ₹5000",
];

// ============================================================
// TRAIN CLASSES
// ============================================================

export const travelClasses = [
  { code: "ALL", label: "All classes" },
  { code: "SL", label: "Sleeper" },
  { code: "3A", label: "AC 3-Tier" },
  { code: "2A", label: "AC 2-Tier" },
  { code: "1A", label: "AC First" },
  { code: "CC", label: "AC Chair" },
  { code: "EC", label: "Exec. Chair" },
];

// ============================================================
// TIME SLOTS
// ============================================================

export const timeSlots = [
  { id: "early", label: "Early", range: "00:00 – 06:00" },
  { id: "morning", label: "Morning", range: "06:00 – 12:00" },
  { id: "afternoon", label: "Afternoon", range: "12:00 – 18:00" },
  { id: "night", label: "Night", range: "18:00 – 24:00" },
];

// ============================================================
// DATA COUNTS — useful for checking the dummy dataset
// ============================================================

export const inventoryCounts = {
  trains: trains.length,
  buses: busRoutes.length,
  flights: flightRoutes.length,
  ferries: ferryRoutes.length,
  metros: metroRoutes.length,
  hotelDestinations: hotelDestinations.length,
  hotels: hotels.length,
};
