/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as PnrRouteImport } from './routes/pnr'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CabberIndexRouteImport } from './routes/cabber.index'
import { Route as CabberDriverRouteImport } from './routes/cabber.driver'
import { Route as BookModeRouteImport } from './routes/book.$mode'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PnrRoute = PnrRouteImport.update({
  id: '/pnr',
  path: '/pnr',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabberIndexRoute = CabberIndexRouteImport.update({
  id: '/cabber/',
  path: '/cabber/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabberDriverRoute = CabberDriverRouteImport.update({
  id: '/cabber/driver',
  path: '/cabber/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const BookModeRoute = BookModeRouteImport.update({
  id: '/book/$mode',
  path: '/book/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/pnr': typeof PnrRoute
  '/rewards': typeof RewardsRoute
  '/trips': typeof TripsRoute
  '/wallet': typeof WalletRoute
  '/api/chat': typeof ApiChatRoute
  '/book/$mode': typeof BookModeRoute
  '/cabber/driver': typeof CabberDriverRoute
  '/cabber/': typeof CabberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/pnr': typeof PnrRoute
  '/rewards': typeof RewardsRoute
  '/trips': typeof TripsRoute
  '/wallet': typeof WalletRoute
  '/api/chat': typeof ApiChatRoute
  '/book/$mode': typeof BookModeRoute
  '/cabber/driver': typeof CabberDriverRoute
  '/cabber': typeof CabberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/pnr': typeof PnrRoute
  '/rewards': typeof RewardsRoute
  '/trips': typeof TripsRoute
  '/wallet': typeof WalletRoute
  '/api/chat': typeof ApiChatRoute
  '/book/$mode': typeof BookModeRoute
  '/cabber/driver': typeof CabberDriverRoute
  '/cabber/': typeof CabberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/complaints'
    | '/dashboard'
    | '/notifications'
    | '/pnr'
    | '/rewards'
    | '/trips'
    | '/wallet'
    | '/api/chat'
    | '/book/$mode'
    | '/cabber/driver'
    | '/cabber/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/complaints'
    | '/dashboard'
    | '/notifications'
    | '/pnr'
    | '/rewards'
    | '/trips'
    | '/wallet'
    | '/api/chat'
    | '/book/$mode'
    | '/cabber/driver'
    | '/cabber'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/complaints'
    | '/dashboard'
    | '/notifications'
    | '/pnr'
    | '/rewards'
    | '/trips'
    | '/wallet'
    | '/api/chat'
    | '/book/$mode'
    | '/cabber/driver'
    | '/cabber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ComplaintsRoute: typeof ComplaintsRoute
  DashboardRoute: typeof DashboardRoute
  NotificationsRoute: typeof NotificationsRoute
  PnrRoute: typeof PnrRoute
  RewardsRoute: typeof RewardsRoute
  TripsRoute: typeof TripsRoute
  WalletRoute: typeof WalletRoute
  ApiChatRoute: typeof ApiChatRoute
  BookModeRoute: typeof BookModeRoute
  CabberDriverRoute: typeof CabberDriverRoute
  CabberIndexRoute: typeof CabberIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnr': {
      id: '/pnr'
      path: '/pnr'
      fullPath: '/pnr'
      preLoaderRoute: typeof PnrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabber/': {
      id: '/cabber/'
      path: '/cabber'
      fullPath: '/cabber/'
      preLoaderRoute: typeof CabberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabber/driver': {
      id: '/cabber/driver'
      path: '/cabber/driver'
      fullPath: '/cabber/driver'
      preLoaderRoute: typeof CabberDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$mode': {
      id: '/book/$mode'
      path: '/book/$mode'
      fullPath: '/book/$mode'
      preLoaderRoute: typeof BookModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ComplaintsRoute: ComplaintsRoute,
  DashboardRoute: DashboardRoute,
  NotificationsRoute: NotificationsRoute,
  PnrRoute: PnrRoute,
  RewardsRoute: RewardsRoute,
  TripsRoute: TripsRoute,
  WalletRoute: WalletRoute,
  ApiChatRoute: ApiChatRoute,
  BookModeRoute: BookModeRoute,
  CabberDriverRoute: CabberDriverRoute,
  CabberIndexRoute: CabberIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
